### ISSUE TITLE
Faulty error mapper for constraint errors

### ISSUE THREAD

**Issue by nItroFreeZer** [go-rel/mysql#62]
The error message cases in the provided code are faulty and there is a missing case for Error 1451.

https://github.com/go-rel/mysql/blob/57be534643f86a0c60e8ea6d708ad46f84a0b994/mysql.go#L132-L143

Suggestion:
```go
	case "Error 1062 (23000)":
		return rel.ConstraintError{
			Key:  sql.ExtractString(msg, "key '", "'"),
			Type: rel.UniqueConstraint,
			Err:  err,
		}
	case "Error 1452 (23000)":
		return rel.ConstraintError{
			Key:  sql.ExtractString(msg, "CONSTRAINT `", "`"),
			Type: rel.ForeignKeyConstraint,
			Err:  err,
		}
	case "Error 1451 (23000)":
		return rel.ConstraintError{
			Key:  sql.ExtractString(msg, "CONSTRAINT `", "`"),
			Type: rel.ForeignKeyConstraint,
			Err:  err,
		}
```

See:
- https://dev.mysql.com/doc/refman/5.7/en/example-foreign-keys.html
- https://dev.mysql.com/doc/refman/8.0/en/example-foreign-keys.html
- https://dev.mysql.com/doc/mysql-errors/8.0/en/server-error-reference.html

**Comment by Fs02** [comment]
Thank you for opening this issue...

do you know what is "23000"? is it static?

**Comment by nItroFreeZer** [comment]
`23000` is the `SQLSTATE` for these Error numbers.

**Comment by nItroFreeZer** [comment]
BTW: My Fix is tested with MariaDB 10.

**Comment by Fs02** [comment]
seems it's failed, maybe no need to match the SQL state making it too strict?

**Comment by nItroFreeZer** [comment]
You separate the error message at the `:`.
The match cases include the SQL states accordingly.
https://github.com/go-rel/mysql/blob/main/mysql.go#L122-L131

**Comment by Fs02** [comment]
I see, seems it's depends whether the driver got SQLState or not
https://github.com/go-sql-driver/mysql/blob/master/errors.go#L70-L76

if you don't mind, can you fix it and add integration test for mariadb as well?

**Comment by nItroFreeZer** [comment]
I have changed the mapping so that it works regardless of whether SQLSTATE is present or not.
Mariadb works as well.

**Comment by Fs02** [comment]
released: https://github.com/go-rel/mysql/releases/tag/v0.12.0
